apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yiht
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-yiht@sha256:2393e7810f6b8c27db2c2980f2caf6a374bd67f5d6d2e183071977833691e703
        name: my-nodejs
        resources: {}
status: {}
